Testing my python skills

I am just writing some basic code to think about how much python knowledge I still have left in me, after not using it for a while.

In [ ]:
# import libraries
import numpy as np
import math
import scipy
import matplotlib.pyplot as plt
import sys

In [48]:
# basic math
print(1+2)
a = 2
b = 3
c = a + b
print(a, b, c)

3
2 3 5


In [16]:
# Text and strings
print("Text with a line break.\nText on new line." )

age = 10
print("You are", age, "years old.")
print("In 5 years you will be", age + 5, "years old.")

name = "Mike"
print("Hello, " + name)
print("Hello,", name)
print(name.upper())
print(len(name))
print(name.replace("M", "N"))

2 3 5
Text with a line break.
Text on new line.
You are 10 years old.
In 5 years you will be 15 years old.
Hello, Mike
Hello, Mike
MIKE
4
Nike


In [35]:
# lists
list1 = [1, 2, 3, 4]
print(list1)

list2 = list1 * 2
print(list2)

print(list1[0], list1[1], list1[-1])

ar = []
for i in range(10):
    ar.append(i)
print(ar)

[1, 2, 3, 4]
[1, 2, 3, 4, 1, 2, 3, 4]
1 2 4
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [51]:
# numpy arrays

ar1 = np.linspace(0, 5, 51)
print(ar1)

ar2 = np.arange(0, 10, 1) # 10 will not be in the array
ar21 = np.arange(0, 10.01, 1) # 10 will be in the array
ar22 = np.arange(10)
ar23 = np.arange(0, 10, 2)
print(ar2, "and", ar21, "and", ar22, "and", ar23)

ar3 = np.array([1, 2, 3, 4]) 
ar4 = np.array([2, 3, 4, 5])
ar5 = ar3 * ar4
ar6 = ar3 * 2
print(ar3, "\n", ar4, "\n", ar5, "\n", ar6)


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5. ]
[0 1 2 3 4 5 6 7 8 9] and [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] and [0 1 2 3 4 5 6 7 8 9] and [0 2 4 6 8]
[1 2 3 4] 
 [2 3 4 5] 
 [ 2  6 12 20] 
 [2 4 6 8]


In [63]:
# matrices
A = np.identity(3)
B = np.matrix(3)
C = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A, "\n", B, "\n", C, "\n", A+C)

print(A[1]) # print second row
print(A[0][2]) # print A_13, third item on first column

print("Trace of matrix A is", np.trace(A))
print("Determinant of matrix \n", A, "\n is \n", np.linalg.det(A)) # det = 1
print("Determinant of matrix \n", C, "\n is \n", np.linalg.det(C)) # det = 0

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
 [[3]] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
[0. 1. 0.]
0.0
Trace of matrix A is 3.0
Determinant of matrix 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
 is 
 1.0
Determinant of matrix 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 is 
 0.0
